---
# custom tasks file for lighttpd on Alpine Linux

- include_tasks: other.yml

- name: Add include to global configuration file for custom configuration
  lineinfile:
    dest: "{{lighttpd_config_file}}"
    line: "include \"{{lighttpd_extra_config_file}}\""
  notify: restart lighttpd

- name: Tweak init file for lighttpd
  lineinfile:
    path: /etc/init.d/lighttpd
    regexp: 'need net'
    state: absent
  notify: restart lighttpd
  when: ansible_connection == "docker"
