---
# custom tasks file for lighttpd on Alpine Linux

- name: Create configuration folder
  file:
    path: "{{lighttpd_config_enabled_path}}"
    state: directory
    owner: root
    group: root

- name: Add include to global configuration file for custom configuration
  lineinfile:
    dest: "{{lighttpd_config_file}}"
    line: "include \"{{lighttpd_extra_config_file}}\""
  notify: restart lighttpd

- name: Tweak init file for lighttpd
  lineinfile:
    path: /etc/init.d/lighttpd
    regexp: 'need net'
    state: absent
  notify: restart lighttpd
  when: ansible_connection == "docker"
