---
# tasks file for lighttpd

- name: Install lighttpd
  package:
    name: "{{lighttpd_packages}}"
    state: present

- include_tasks: "{{ansible_os_family | lower}}.yml"
  when: ansible_os_family == 'Alpine'

- name: Find global configuration options
  command: >
    awk  '/^{{lighttpd_config | join("|") }}/{ print($1) }' {{lighttpd_config_file}}
  register: lighttpd_find_options
  when: lighttpd_config is defined
  changed_when: false

- name: Register global configuration options
  set_fact:
    lighttpd_global_options: "{{lighttpd_find_options.stdout_lines}}"
  when: lighttpd_config is defined

- name: Global configuration options overrides
  lineinfile:
    path: "{{lighttpd_config_file}}"
    regexp: "^{{item}}"
    line: "{{item}} = {{lighttpd_config[item]}}"
  with_items: "{{lighttpd_config}}"
  when: lighttpd_config is defined and item in lighttpd_global_options

- name: Enable lighttpd service
  service:
    name: "{{lighttpd_service}}"
    enabled: true

- name: Create configuration file
  template:
    src: lighttpd.conf.j2
    dest: "{{lighttpd_extra_config_file}}"
    lstrip_blocks: true
  notify: restart lighttpd

