---
# tasks file for lighttpd

- name: Include OS specific configuration values
  include_vars: "{{ config_file }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
        - "{{ ansible_system | lower }}.yml"
      paths:
        - "{{ role_path }}/vars"
  loop_control:
    loop_var: config_file

- name: Install lighttpd
  package:
    name: "{{ lighttpd_packages }}"
    state: present

- include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
        - "{{ ansible_system | lower }}.yml"
        - other.yml
      paths:
        - "{{ role_path }}/tasks"


- name: Find global configuration options
  command: >
    awk  '/^{{ lighttpd_config | join("|") }}/{ print($1) }' {{ lighttpd_config_file }}
  register: lighttpd_find_options
  when: lighttpd_config is defined
  changed_when: false
  check_mode: false

- name: Register global configuration options
  set_fact:
    lighttpd_global_options: "{{ lighttpd_find_options.stdout_lines }}"
  when: lighttpd_config is defined

- name: Global configuration options overrides
  lineinfile:
    path: "{{ lighttpd_config_file }}"
    regexp: "^{{ item }}"
    line: "{{ item }} = {{ lighttpd_config[item] }}"
  with_items: "{{ lighttpd_config }}"
  when: lighttpd_config is defined and item in lighttpd_global_options

- name: Create configuration file
  template:
    src: lighttpd.conf.j2
    dest: "{{ lighttpd_extra_config_file }}"
    lstrip_blocks: true
    mode: 0644
  notify: restart lighttpd

- name: Disable IPv6 support
  lineinfile:
    path: "{{ lighttpd_config_file }}"
    regexp: '^(server.use-ipv6.+)'
    line: '#\1'
    backrefs: true
  notify: restart lighttpd

- name: Enable lighttpd service
  service:
    name: "{{ lighttpd_service }}"
    enabled: true
