---
# tasks file for lighttpd

- name: Install lighttpd
  package:
    name: "{{lighttpd_packages}}"
    state: present

- name: Setup default server port
  lineinfile:
    path: "{{lighttpd_config_file}}"
    state: present
    regexp: "^server.port"
    line: "server.port = {{lighttpd_server_port}}"
  when: lighttpd_server_port is defined

- name: Create configuration file
  template:
    src: lighttpd.conf.j2
    dest: "{{lighttpd_extra_config_file}}"
  notify: restart lighttpd

- name: Enable and start lighttpd service
  service:
    name: "{{lighttpd_service}}"
    enabled: true
    state: started
