# Non-Debian OS/distribution tasks
---

- name: Create configuration paths
  file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
    mode: 0755
  loop:
    - "{{ lighttpd_sites_available_path }}"
    - "{{ lighttpd_sites_enabled_path }}"
    - "{{ lighttpd_config_available_path }}"
    - "{{ lighttpd_config_enabled_path }}"

- name: Prepare global configuration file for custom configuration
  lineinfile:
    dest: "{{ lighttpd_config_file }}"
    regex: 'include-conf-enabled\.pl'
    state: absent
  notify: restart lighttpd

- name: Add include to global configuration file for custom configuration
  lineinfile:
    dest: "{{ lighttpd_config_file }}"
    line: "include \"{{ lighttpd_config_enabled_path }}/*.conf\""
  notify: restart lighttpd

- name: Add include to global configuration file for enabled sites
  lineinfile:
    dest: "{{ lighttpd_config_file }}"
    line: "include \"{{ lighttpd_sites_enabled_path }}/*.conf\""
  notify: restart lighttpd
