# Non-Debian OS/distribution tasks
---

- name: Create configuration paths
  file:
    path: "{{item}}"
    owner: root
    group: root
    state: directory
  loop:
    - "{{lighttpd_sites_available_path}}"
    - "{{lighttpd_sites_enabled_path}}"
    - "{{lighttpd_config_available_path}}"
    - "{{lighttpd_config_enabled_path}}"
