# Non-Debian OS/distribution tasks
---

- name: Create configuration paths
  file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
    mode: 0755
  loop:
    - "{{ lighttpd_sites_available_path }}"
    - "{{ lighttpd_sites_enabled_path }}"
    - "{{ lighttpd_config_available_path }}"
    - "{{ lighttpd_config_enabled_path }}"

- name: Add include to global configuration file for custom configuration
  lineinfile:
    dest: "{{ lighttpd_config_file }}"
    line: "include \"{{ lighttpd_extra_config_file }}\""
  when:
    - lighttpd_config is defined or lighttpd_modules is defined
    - ansible_os_family != 'Debian'
  notify: restart lighttpd
