---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: lighttpd-alpine-3.9
    image: alpine:3.9
    volumes:
      - "/mnt/mirrors/alpine/3.9:/var/cache/apk"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    capabilities:
      - SYS_ADMIN
    command: /sbin/init
  - name: lighttpd-alpine-3.10
    image: alpine:3.9
    volumes:
      - "/mnt/mirrors/alpine/3.10:/var/cache/apk"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    capabilities:
      - SYS_ADMIN
    command: /sbin/init
  - name: lighttpd-alpine-3.11
    image: alpine:3.9
    volumes:
      - "/mnt/mirrors/alpine/3.11:/var/cache/apk"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    capabilities:
      - SYS_ADMIN
    command: /sbin/init
  - name: lighttpd-debian-stable
    image: debian:stable
    volumes:
      - "/mnt/mirrors/debian/stable:/var/cache/apt/archives"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    capabilities:
      - SYS_ADMIN
    command: /lib/systemd/systemd
  - name: lighttpd-ubuntu-16.04
    image: ubuntu:16.04
    volumes:
      - "/mnt/mirrors/ubuntu/16.04:/var/cache/apt/archives"
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    capabilities:
      - SYS_ADMIN
    command: /sbin/init
  - name: lighttpd-ubuntu-18.04
    image: ubuntu:18.04
    volumes:
      - "/mnt/mirrors/ubuntu/18.04:/var/cache/apt/archives"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    capabilities:
      - SYS_ADMIN
    command: /sbin/init
  - name: lighttpd-ubuntu-20.04
    image: ubuntu:18.04
    volumes:
      - "/mnt/mirrors/ubuntu/20.04:/var/cache/apt/archives"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    capabilities:
      - SYS_ADMIN
    command: /sbin/init
provisioner:
  name: ansible
  # log: true
  config_options:
    defaults:
      interpreter_python: auto_silent
  playbooks:
    prepare: ../common/prepare.yml
    converge: ../common/playbook.yml
    lint: |
      set -e
      yamllint .
      ansible-lint
      flake8
scenario:
  name: default
